### PR TITLE
2021 04 29 implement speed test using standalone framework

### PR DESCRIPTION
**Pull request by siqiyyyy**
A simple test with 100 FIFO and 1000000 cycles takes 4 seconds, corresponding to 25MHZ

### CODE REVIEW

**Comment by siqiyyyy** [comment]
re-implemented the test for fifo verification. Currently the signal propagation doesn't seem to work. Verified that the propagate() functions are called.

**Comment by AndreasAlbert** [comment]
nice, good stuff! Let's figure out the fifo propagation after merging.

**Comment by AndreasAlbert** [comment]
> A simple test with 100 FIFO and 1000000 cycles takes 4 seconds, corresponding to 25MHZ
Wait, you mean total rate = 25 MHz / nFifo, right? so 25 MHz / 100 = 250 kHz?

**Comment by AndreasAlbert** [comment]
Also, is it possible you have one too may zeros there? I get this result:
```
100-FIFO Circuit run 1000000 cycles in 30 seconds. Rate: 33 kHz
```

**Comment by siqiyyyy** [comment]
Ahh yes! Then that gives you 33kHZ for 100 FIFO, which means 3.3MHZ per fifo

**Pull request merged**
